name: "Build Godot"
description: "Build a Godot project for multiple platforms"
author: josephbmanley

inputs:
  name:
    description: 'Name of the exported binary'
    required: true
  preset:
    description: 'Name of the preset in `export_presets.cfg` to use'
    required: true
  subdirectory:
    description: 'Optional name of the subdirectory to put exported project in'
    default: ""
  package:
    description: 'Set true to output an artifact zip file'
    default: false
  projectDir:
    description: 'Location of Godot project in repository'
    default: "."
  debugMode:
    description: 'Whether or not to use `--export-debug`'
    default: false

runs:
  using: docker
  image: docker://godotengine/godot:4.2
  args:
    - ${{ inputs.name }}
    - ${{ inputs.preset }}
    - ${{ inputs.subdirectory }}
    - ${{ inputs.package }}
    - ${{ inputs.projectDir }}
    - ${{ inputs.debugMode }}
  steps:
    - name: Choose Export Flag
      id: export_flag
      run: |
        if [ "${{ inputs.debugMode }}" == "true" ]; then
          echo "export_flag=--export-debug" >> $GITHUB_ENV
        else
          echo "export_flag=--export-release" >> $GITHUB_ENV
    - name: Build Project
      run: |
        godot ${{ env.export_flag }} ${{ inputs.preset }}

