extends Sprite2D

@onready var _1 = $"1"
@onready var _2 = $"2"
@onready var _3 = $"3"
@onready var _4 = $"4"
@onready var _5 = $"5"
@onready var _6 = $"6"
@onready var _7 = $"7"
@onready var _8 = $"8"
@onready var _9 = $"9"
@onready var _10 = $"10"
@onready var _11 = $"11"
@onready var _12 = $"12"
@onready var _13 = $"13"
@onready var _14 = $"14"
@onready var _15 = $"15"

var skill = Global.fishing

func _process(_delta):
	if skill == 0:
		_1.visible = false
		_2.visible = false
		_3.visible = false
		_4.visible = false
		_5.visible = false
		_6.visible = false
		_7.visible = false
		_8.visible = false
		_9.visible = false
		_10.visible = false
		_11.visible = false
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 1:
		_1.visible = true
		_2.visible = false
		_3.visible = false
		_4.visible = false
		_5.visible = false
		_6.visible = false
		_7.visible = false
		_8.visible = false
		_9.visible = false
		_10.visible = false
		_11.visible = false
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 2:
		_1.visible = true
		_2.visible = true
		_3.visible = false
		_4.visible = false
		_5.visible = false
		_6.visible = false
		_7.visible = false
		_8.visible = false
		_9.visible = false
		_10.visible = false
		_11.visible = false
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 3:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = false
		_5.visible = false
		_6.visible = false
		_7.visible = false
		_8.visible = false
		_9.visible = false
		_10.visible = false
		_11.visible = false
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 4:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = false
		_6.visible = false
		_7.visible = false
		_8.visible = false
		_9.visible = false
		_10.visible = false
		_11.visible = false
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 5:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = true
		_6.visible = false
		_7.visible = false
		_8.visible = false
		_9.visible = false
		_10.visible = false
		_11.visible = false
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 6:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = true
		_6.visible = true
		_7.visible = false
		_8.visible = false
		_9.visible = false
		_10.visible = false
		_11.visible = false
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 7:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = true
		_6.visible = true
		_7.visible = true
		_8.visible = false
		_9.visible = false
		_10.visible = false
		_11.visible = false
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 8:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = true
		_6.visible = true
		_7.visible = true
		_8.visible = true
		_9.visible = false
		_10.visible = false
		_11.visible = false
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 9:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = true
		_6.visible = true
		_7.visible = true
		_8.visible = true
		_9.visible = true
		_10.visible = false
		_11.visible = false
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 10:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = true
		_6.visible = true
		_7.visible = true
		_8.visible = true
		_9.visible = true
		_10.visible = true
		_11.visible = false
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 11:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = true
		_6.visible = true
		_7.visible = true
		_8.visible = true
		_9.visible = true
		_10.visible = true
		_11.visible = true
		_12.visible = false
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 12:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = true
		_6.visible = true
		_7.visible = true
		_8.visible = true
		_9.visible = true
		_10.visible = true
		_11.visible = true
		_12.visible = true
		_13.visible = false
		_14.visible = false
		_15.visible = false
	elif skill == 13:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = true
		_6.visible = true
		_7.visible = true
		_8.visible = true
		_9.visible = true
		_10.visible = true
		_11.visible = true
		_12.visible = true
		_13.visible = true
		_14.visible = false
		_15.visible = false
	elif skill == 14:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = true
		_6.visible = true
		_7.visible = true
		_8.visible = true
		_9.visible = true
		_10.visible = true
		_11.visible = true
		_12.visible = true
		_13.visible = true
		_14.visible = true
		_15.visible = false
	elif skill == 15:
		_1.visible = true
		_2.visible = true
		_3.visible = true
		_4.visible = true
		_5.visible = true
		_6.visible = true
		_7.visible = true
		_8.visible = true
		_9.visible = true
		_10.visible = true
		_11.visible = true
		_12.visible = true
		_13.visible = true
		_14.visible = true
		_15.visible = true
