name: Build Godot
description: Build Godot with the provided options.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SCons cache directory
        run: mkdir -p "${{ github.workspace }}/.scons-cache"

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y scons

      - name: SCons Build
        env:
          SCONSFLAGS: ${{ inputs.sconsflags }}
          SCONS_CACHE: ${{ inputs.scons-cache }}
          SCONS_CACHE_LIMIT: ${{ inputs.scons-cache-limit }}
        run: |
          echo "Building with flags:" ${{ env.SCONSFLAGS }}
          if [ "${{ inputs.buildroot }}" != "" ]; then
            echo "Using buildroot at ${{ inputs.buildroot }}"
            export PATH="${{ inputs.buildroot }}:$PATH"
          fi
          scons p=${{ inputs.platform }} target=${{ inputs.target }} tools=${{ inputs.tools }} tests=${{ inputs.tests }} ${{ env.SCONSFLAGS }}
          ls -l bin/
