name: Godot Exporter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Exporter:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/greenfox/godot-build-automation:latest
    steps:
    - uses: actions/checkout@v2
    - name: Export Godot Project
      run: |
        exporter            
    - name: Deploy To Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
